### ISSUE TITLE
bug: PgSearchFilter missing Debug + Serialize + Deserialize — breaks dynamic_context in rig-core v0.27 when using PostgresVectorStore

### ISSUE THREAD

**Issue by sungaoyong** [0xPlaygrounds/rig#1186]
🧾 Description
After upgrading to rig-core v0.27, my RAG agent initialization code fails to compile when using PostgresVectorStore with AgentBuilder::dynamic_context(). The error occurs because PgSearchFilter does not implement the required traits: std::fmt::Debug, serde::Serialize, and serde::Deserialize<'de>.

This appears to be due to stricter trait bounds introduced in rig-core v0.27 on the VectorStoreIndexDyn trait.

 Reproduction Code
Here’s the relevant part of my agent constructor:
`pub async fn new(config: BidConfig) -> Self {
    let base_url = config.api.base_url.as_str();
    let embedding_model = config.api.embedding_model.as_str();
    let model = config.api.model.as_str();
    let max_retries = config.api.max_retries;

    // Ensure base_url doesn't end with slash
    let clean_base_url = if base_url.ends_with('/') {
        &base_url[..base_url.len() - 1]
    } else {
        base_url
    };

    let client: ollama::Client = ollama::Client::builder()
        .api_key(Nothing)
        .base_url(clean_base_url)
        .build()
        .unwrap();

    let embedding_model = client.embedding_model_with_ndims(embedding_model, 1024);

    let pool = PgPoolOptions::new()
        .max_connections(50)
        .idle_timeout(std::time::Duration::from_secs(5))
        .connect(&config.api.vector_db_link)
        .await
        .expect("Failed to create postgres pool");

    let vector_store = PostgresVectorStore::with_defaults(embedding_model, pool);

    // This line fails to compile in rig-core 0.27
    let agent = client.agent(&model.to_string())
        .dynamic_context(3, vector_store)
        .build();

    Self {
        client,
        model: model.to_string(),
        max_retries,
        db_client: None,
        agent: Arc::new(agent),
    }
}`
Compilation Errors
`error[E0277]: `PgSearchFilter` doesn't implement `std::fmt::Debug`
  --> src/utils/rag_agent.rs:66:33
   |
66 |             .dynamic_context(3, vector_store)
   |              ---------------    ^^^^^^^^^^^^ the trait `std::fmt::Debug` is not implemented for `PgSearchFilter`

error[E0277]: the trait bound `PgSearchFilter: serde::Serialize` is not satisfied
  --> src/utils/rag_agent.rs:66:33
   |
66 |             .dynamic_context(3, vector_store)
   |              ---------------    ^^^^^^^^^^^^ the trait `serde::Serialize` is not implemented for `PgSearchFilter`

error[E0277]: the trait bound `PgSearchFilter: serde::Deserialize<'de>` is not satisfied
  --> src/utils/rag_agent.rs:66:33
   |
66 |             .dynamic_context(3, vector_store)
   |              ---------------    ^^^^^^^^^^^^ the trait `for<'de> Deserialize<'de>` is not implemented for `PgSearchFilter`
`

The errors point to this requirement in rig-core:
`// In AgentBuilder::dynamic_context
dynamic_context: impl VectorStoreIndexDyn + Send + Sync + 'static,`

And VectorStoreIndexDyn requires the associated Filter type to implement:

Debug
Serialize
Deserialize<'de>
🔍 Root Cause
In crates/rig-postgres/src/lib.rs, PgSearchFilter is defined as:

#[derive(Clone, Default)]
pub struct PgSearchFilter {
    condition: String,
    values: Vec<serde_json::Value>,
}

It lacks Debug, Serialize, and Deserialize derives, even though its fields (String and Vec<serde_json::Value>) fully support them.

 Proposed Fix
Simply add the missing derives:

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PgSearchFilter {
    condition: String,
    values: Vec<serde_json::Value>,
}

This change is:

Safe: all fields already implement the required traits.
Backward-compatible: no API breakage.
Minimal: one-line fix.
 Environment
rig-core: 0.27.0
rig-postgres: 0.1.28
Rust: 1.78+ (stable)
OS: Windows / Linux / macOS (irrelevant, compilation issue)
Offer to Help
I’m happy to open a PR with the fix if you’d like! It’s a tiny but critical change for anyone using PostgreSQL vector storage with dynamic context in rig-core v0.27+.

Note: Other vector store implementations in the rig ecosystem (e.g., rig-qdrant, rig-weaviate, etc.) might have similar issues if their filter types also lack Debug + Serialize + Deserialize. It may be worth auditing them for compatibility with the new VectorStoreIndexDyn bounds.

Thank you for building rig — it’s a great framework!

**Comment by joshua-mo-143** [comment]
Hi @sungaoyong! Thanks for opening this issue.

Looks like this was unfortunately caused by an oversight. We'll open a merge fix for this shortly as this appears to be a relatively severe bug, although not critical enough that it'd warrant re-releasing everything right before Christmas.

**Comment by ereztdev** [comment]
Seems like this bug/issue has been resolved?

**Comment by joshua-mo-143** [comment]
Yes, this issue has been resolved! Closing now.

Please reach out again if you guys find any more issues  🙂
